### ISSUE TITLE
AttributeError: 'RestData' object has no attribute 'update' - 0.117 issues?

### ISSUE THREAD

**Issue by DavidFW1960** [exxamalte/home-assistant-customisations#3]
I am getting the following issues with version 0.117
```
2020-10-23 09:44:55 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up nsw_rural_fire_service_fire_danger platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/nsw_rural_fire_service_fire_danger/sensor.py", line 65, in setup_platform
    rest.update()
AttributeError: 'RestData' object has no attribute 'update'
```

**Comment by exxamalte** [comment]
Thanks for reporting this. Most likely this is caused by making the `rest` integration code async: https://github.com/home-assistant/core/pull/41973
