### ISSUE TITLE
hass 2020.12.0 comes with TypeError

### ISSUE THREAD

**Issue by jurgenweber** [exxamalte/home-assistant-customisations#5]
```2020-12-16 08:24:55 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up nsw_rural_fire_service_fire_danger platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/nsw_rural_fire_service_fire_danger/sensor.py", line 64, in async_setup_platform
    rest = RestData(
TypeError: __init__() missing 1 required positional argument: 'verify_ssl'```

**Comment by exxamalte** [comment]
This has already been fixed in the new repository: https://github.com/exxamalte/home-assistant-custom-components-nsw-rural-fire-service-fire-danger

I will add a link in this repository later, to point users to the new HACS-compatible one.
